@echo off
setlocal enabledelayedexpansion

rem ============================================================
rem Combine selected source files into one text file
rem Skips any file whose full path contains a directory
rem from IGNORE_DIRS.
rem Output: combined_source.txt
rem ============================================================

rem Derive output name from the current directory's root-relative path
set "DRIVELESS=%CD:~2%"
if not "!DRIVELESS!"=="" if "!DRIVELESS:~0,1!"=="\" set "DRIVELESS=!DRIVELESS:~1!"
set "OUTPUT_BASENAME=!DRIVELESS:\=_!"
set "OUTPUT_BASENAME=!OUTPUT_BASENAME: =_!"
set "OUTPUT=!OUTPUT_BASENAME!_combined.txt"

set "SOURCE_DIR=%cd%"

rem Space- or semicolon-separated list of directory names to ignore
rem Example defaults; edit as needed
set "IGNORE_DIRS=.git node_modules dist build bin obj .venv .vs __pycache__ .pytest_cache downloads logs scripts gen3sys_balenacore.egg-info shared"

set "FOROPTS=/r "%SOURCE_DIR%""

> "%OUTPUT%" (
  echo ===========================================================
  echo GPT CONTEXT:
  echo This file was generated by a batch script combining source files
  echo from the following directory:
  echo.
  echo %SOURCE_DIR%
  echo.
  echo Each file below is wrapped in clear BEGIN/END markers.
  echo ===========================================================
  echo.
)

for %FOROPTS% %%F in (*.py *.tsx *.sql *.ts) do (
  if exist "%%F" (
    rem Skip if output file itself
    if /i "%%~nxF"=="%OUTPUT%" (
      rem skip
    ) else (
      rem Check against ignore list using string substitution
      set "SKIP="
      set "FULLPATH=%%~fF"
      for %%D in (%IGNORE_DIRS%) do (
        set "TESTPATH=!FULLPATH:\%%D\=!"
        if not "!TESTPATH!"=="!FULLPATH!" set "SKIP=1"
      )
      if not defined SKIP (
        (
          echo ===========================================================
          echo ===== BEGIN FILE: %%~fF =====
          echo ===========================================================
          echo.
          type "%%F"
          echo.
          echo ===========================================================
          echo ===== END FILE: %%~fF =====
          echo ===========================================================
          echo.
          echo.
        )>> "%OUTPUT%"
      )
    )
  )
)

echo Done. Combined files written to %OUTPUT%.
endlocal
pause
