@echo off
setlocal enabledelayedexpansion

rem ============================================================
rem Combine .cpp, .h, .txt, and .md files into one text file
rem Include full source directory path at the top.
rem Output: combined_source.txt
rem ============================================================

set OUTPUT=combined_source.txt
set SOURCE_DIR=%cd%

set "FOROPTS="
if /i "%~1"=="-r" set FOROPTS=/r "%SOURCE_DIR%"

echo =========================================================== > "%OUTPUT%"
echo GPT CONTEXT: >> "%OUTPUT%"
echo This file was generated by a batch script combining source files >> "%OUTPUT%"
echo from the following directory: >> "%OUTPUT%"
echo. >> "%OUTPUT%"
echo %SOURCE_DIR% >> "%OUTPUT%"
echo. >> "%OUTPUT%"
echo Each file below is wrapped in clear BEGIN/END markers. >> "%OUTPUT%"
echo =========================================================== >> "%OUTPUT%"
echo. >> "%OUTPUT%"

for %FOROPTS% %%F in (*.cpp *.h *.c *.cxx *.hxx *.txt *.md Makefile CMakeLists.txt .gitlab-ci.yml Dockerfile vcpkg.json) do (
    if exist "%%F" (
        echo %%F | findstr /i "\\.git\\" >nul
        if errorlevel 1 (
            if /i not "%%~nxF"=="%OUTPUT%" (
                echo =========================================================== >> "%OUTPUT%"
                echo ===== BEGIN FILE: %%~fF ===== >> "%OUTPUT%"
                echo =========================================================== >> "%OUTPUT%"
                echo. >> "%OUTPUT%"

                type "%%F" >> "%OUTPUT%"

                echo. >> "%OUTPUT%"
                echo =========================================================== >> "%OUTPUT%"
                echo ===== END FILE: %%~fF ===== >> "%OUTPUT%"
                echo =========================================================== >> "%OUTPUT%"
                echo. >> "%OUTPUT%"
                echo. >> "%OUTPUT%"
            )
        )
    )
)

echo Done. Combined files written to %OUTPUT%.
endlocal
pause


